### ISSUE TITLE
Lenses?

### ISSUE THREAD

**Issue by snoyberg** [snoyberg/codename-karka#2]
What support, if any, should we provide for lenses? Should we provide the implementation in rio itself, or import it from a package like microlens?

**Comment by kerscher** [comment]
`microlens` itself depends only on `base`. It’s `microlens-platform` that brings in more things and interfaces to common typeclasses etc.

**Comment by chrisdone** [comment]
+1 on microlens.

**Comment by snoyberg** [comment]
OK, for now I'm going with a dep on the microlens package itself and nothing else. Thanks!
