### ISSUE TITLE
Depend on clock?

### ISSUE THREAD

**Issue by snoyberg** [snoyberg/codename-karka#3]
We can probably provide some very useful helpful functions, like `logTimed`. We already do stuff like this in Stack for running external processes, and can generalize it.

**Comment by chrisdone** [comment]
The clock package apparently has weird bugs. I think we could copy/paste the timing code from Criterion which works reliably: https://hackage.haskell.org/package/criterion-1.2.6.0/docs/Criterion-Measurement.html

In favor of including `logTimed` (assuming something like `MonadLogger m => m a -> m a` is what you're talking about).

**Comment by snoyberg** [comment]
See https://github.com/fpco/unliftio/pull/15

**Comment by snoyberg** [comment]
`getMonotonicTime` added to unliftio, closing.
