### ISSUE TITLE
Data structure typeclasses or not?

### ISSUE THREAD

**Issue by snoyberg** [snoyberg/codename-karka#4]
Both foundation and mono-traversable have created sets of typeclasses for representing various data structures (sequences, maps, sets). The question is: should rio do this too?

__Advantages__

* The prelude will be more useful, working on many different data types
* It may make it easier to support new data types in the future

__Disadvantages__

* Adding an extra dependency on mono-traversable (alternatively: move those typeclasses into rio and have mono-traversable depend on rio instead)
* It seems like the general "best practice" in the community is to use qualified imports, and we may not want to buck that trend here

Regardless, I believe we should provide the `RIO.ByteString`, `RIO.Text`, etc re-export modules for those who want qualified imports, or for cases where the typeclasses would get in the way.

**Comment by kerscher** [comment]
`microlens` itself depends only on `base`. It’s `microlens-platform` that brings in more things and interfaces to common typeclasses etc.

**Comment by kerscher** [comment]
If and when `mono-traversable` or `foundation` gets added for the typeclasses, there should be documentation for new users on what the error messages mean, since it’s not clearly obvious how to read if you don’t know the typeclasses and Haskell features used on them already.

**Comment by snoyberg** [comment]
From discussions yesterday, it sounds like we will _not_ be introducing something like mono-traversable for now.
