### ISSUE TITLE
Bikeshed: library name

### ISSUE THREAD

**Issue by snoyberg** [snoyberg/codename-karka#8]
What should we call the main library name? `rio` is the work-in-progress name. CC @chrisdone

**Comment by chrisdone** [comment]
I'm going to take back my request to bikeshed. rio works for me.

**Comment by kerscher** [comment]
I can’t help but think of this:
![Rio de Janeiro](https://www.ahstatic.com/photos/city/vi-v6871_00_1400x442.jpg)

“Write code as if chilling at the beach, instead of on the cold Scottish winter!”

**Comment by snoyberg** [comment]
To make this as simple as possible, I'm going to put three different name choices as comments. If you like that name: give it a thumbs up reaction. If you dislike that name, give it a thumbs down. If you have a different idea, post a comment.

**Comment by snoyberg** [comment]
rio

**Comment by snoyberg** [comment]
jump

**Comment by snoyberg** [comment]
karka

**Comment by kerscher** [comment]
prologue

**Comment by kerscher** [comment]
preface

**Comment by kerscher** [comment]
basics

**Comment by snoyberg** [comment]
Looks like we're going with `rio` after all.
